### PR TITLE
add: smart drive checking in setup script and developer install mode

### LINKED ISSUE #28: [SETUP] Intelligently mount the drive
If drive not ext4 => reformat and mount
else => mount ext4
scan files on drive to determine if it's from previous installation
If drive is familiar => done
Else => format and mount

Before formatting, warn the user and get confirmation.
exit setup if format permission not granted

### PR DESCRIPTION
**Pull request by nullcount**
The setup.sh script now has a dev mode! It will install dev dependencies like yarn and python virtualenv!
The script will also check your HDD and ask you before formatting it if needed.

Closes #28

### CODE REVIEW

**Comment by nullcount** [comment]
Ok, this should be ready for testing. Checkout this branch locally and follow the readme for setting up the dev environment.

If you encounter any errors or have to run anything other than whats in the readme, report it here.

**Comment by WalterCBlue** [comment]
Only thing I had to do from a user perspective is
login to pi, 
start super user mode 
navigate to the root folder 
proceed to git clone, checkout and run bash scripts/setup.
Everything after that was was intuitive.

Trying to do it out of super user mode did not work for me.

**Comment by nullcount** [comment]
@WalterCBlue thanks for testing! You bring up a good point. I will add an "admin check" to the script and elevate privilege/ask for password if the script is not run as root.

**Comment by davisv7** [comment]
setup_script_error

**Comment by davisv7** [comment]
Problems I faced while trying to run the setup script:

* Where exactly to clone the repo?
* home directory != /home, it's actually /home/pi
* when running as super user, home directory is /root
* The script recognized my drive and that it needed reformatting, but it did not finish formatting my hard drive. When rerunning the script, it fails at check to see if primary storage exists, ~line 44.


A couple of improvements that could be made:

* add the installation of yarn/docker to setup script
* when running the servers manually, there are requirements missing from requirements.txt, I recommend using pipreqs



I'm going to format the drive and retry.

**Comment by nullcount** [comment]
@davisv7 

> Where exactly to clone the repo?

I changed how the defaults.sh and functions.sh are imported. It no longer relies on the project folder being in the home directory. You should be able to clone the repo anywhere now.

>The script recognized my drive and that it needed reformatting, but it did not finish formatting my hard drive. When rerunning the script, it fails at check to see if primary storage exists, ~line 44.

Your drive has a bad superblock. It is in a bad state and the script can't help you. If the script is what caused of your drive to reach a bad state, we should fix that bug. Please try again after fixing your drive.

> add the installation of yarn/docker to setup script

Docker is installed by the script. To install yarn you have to run the script with the `--dev` argument

> ... I recommend using pipreqs

PRs are welcome!

**Review by asharron — APPROVED** [review]

**Pull request merged**
